# Generated by Django 3.2.15 on 2022-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
