# Generated by Django 3.2.15 on 2022-10-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonapp', '0004_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
