# Generated by Django 3.2.15 on 2022-10-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonapp', '0005_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='pics')),
                ('decription', models.TextField()),
            ],
        ),
    ]
