# Generated by Django 3.2.15 on 2022-10-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeonapp', '0006_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='username',
            new_name='member',
        ),
    ]
